import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { AppProvider } from "./AppProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken')

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider initialSessionToken={sessionToken?.value}>
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
