import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'
import { AppProvider } from './AppProvider'
import { cookies } from 'next/headers'
import { Toaster } from '@/components/ui/toaster'
import TanstackProvider from './tanstack-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <TanstackProvider>{children}</TanstackProvider>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
